#!/bin/sh

ENABLED=yes
PROCS=smartdns-china
ARGS="-c /opt/share/smartdns/china.conf -p /opt/var/run/smartdns-china.pid"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/share/smartdns

. /opt/etc/init.d/rc.func
