#!/bin/sh

if [ "$1" == "start" ] || [ "$1" == "restart" ]; then
    /opt/share/chinaipsets/update.sh
fi

ENABLED=yes
PROCS=chinadns-ng
ARGS="-b 127.0.0.1 -l 15353 -c 127.0.0.1#20053 -t 127.0.0.1#20054 -4 chinaip4 -6 chinaip6 -g /opt/share/chinadns-ng/gfwlist.txt -m /opt/share/chinadns-ng/chinalist.txt -o 3 -p 1 -f -r"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/share/chinadns-ng

. /opt/etc/init.d/rc.func
