#!/bin/sh

ENABLED=yes
PROCS=AdGuardHome
ARGS="-c /opt/share/adguardhome/AdGuardHome.yml -w /opt/share/adguardhome"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/share/adguardhome

. /opt/etc/init.d/rc.func
